### PR TITLE
Expansion of the demos library.

### PR DESCRIPTION
**Pull request by joseedil**
I've written additional demos, mainly using the Synchronous MoC. 

Also, there is a refactor on the library structure to fit future expansions.

You may want to review the license terms and keep Ingo as the main author.

### CODE REVIEW

**Comment by ingo-sander** [comment]
Did you use a special license? I think we should use BSD3. The whole Haskell community uses this license.

Do you see some problems? Otherwise I can merge it. I trust you!

**Comment by joseedil** [comment]
No Ingo, I have no problems with BSD license, but you might agree with keeping a list of the contributors on the license file.
Also, keeping a nice changelog file would be useful, but that involves having release versions and can be discussed later.
Finally, @ugeorge told he is going to run the demos to see if everything is ok before merging the repositories. I see no problems but I have only tested them on my Mac machine.

**Comment by ugeorge** [comment]
As concerning the license file, I can see three alternatives to proceed:

 1. one license file with @ingo-sander's name and each application mentioning the actual author. 
 1. one license file with a list of authors  for copyright, and each application mentioning the actual author.
 1. one license file per application, i.e. each application being copyrighted by its respective author,

The first two alternatives seem appropriate if this repository will continue to be a standalone project, separated from any library. The last alternative would make sense if we merge this repository with a ForSyDe library, where the library itself has different authors from the examples.

**Comment by ugeorge** [comment]
A good way to deal with issues regarding both dependencies and licensing is to separate each application as a standalone project (i.e. with an own .cabal file). The drawback may be that the haddock documentation won't be so pretty, but that can be taken care of once we set up a web site template to gather the documentation under one page.

**Pull request merged**
